name: influxdb_example
description: Influx db client example
version: 0.0.1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  pedantic: ^1.8.0
  extra_pedantic: ^1.1.1+3
  binance: ^1.0.1
  influxdb:
    path: ../
