name: influxdb
description: Influx db client. Read and write data to Influxdb 2
homepage: https://github.com/synw/influxdb
version: 0.0.1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  pedantic: ^1.8.0
  extra_pedantic: ^1.1.1+3
  meta: ^1.1.8
  dio: ^3.0.9

dev_dependencies:
  test: ^1.14.2
  test_coverage: ^0.4.1
